version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: build
      include: scope
    groups:
      java-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: ci
      include: scope
    groups:
      github-action-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
