from_latest_tag = true
ignore_merge_commits = true
tag_prefix = "v" # This is important to enable latest tag check with you use v prefix
#disable_changelog = false
#disable_bump_commit = false
#generate_mono_repository_global_tag = true
#generate_mono_repository_package_tags = true
branch_whitelist = ['main']
skip_ci = "[skip ci]"
#skip_untracked = false
pre_bump_hooks = []
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks]

[commit_types]
build = { changelog_title = "Build", bump_patch = true }

[changelog]
path = "CHANGELOG.md"
authors = [
    { username = "abhisheksr01", signature = "Abhishek Rajput" }
]

[bump_profiles]

[packages]
