misconfiguration:
  scanners:
    - dockerfile
    - helm
    - kubernetes

severity:
#  - UNKNOWN # Tracking the issue here: https://github.com/abhisheksr01/spring-boot-microservice-best-practices/issues/351
#  - LOW
#  - MEDIUM
#  - HIGH
  - CRITICAL
